const createDefaultPermissions = () => ({
  bookings: {
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  rooms: {
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  guests: {
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  staff: {
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  payments: {
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  menuItems: {
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  resturantOrders: {
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  maintenanceRequests: {
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  reports: {
    create: false,
    read: false,
    update: false,
    delete: false,
  },
});

const rolePermissions = {
  superadmin: {
    bookings: { create: true, read: true, update: true, delete: true },
    rooms: { create: true, read: true, update: true, delete: true },
    guests: { create: true, read: true, update: true, delete: true },
    staff: { create: true, read: true, update: true, delete: true },
    payments: { create: true, read: true, update: true, delete: true },
    menuItems: { create: true, read: true, update: true, delete: true },
    restaurantOrders: { create: true, read: true, update: true, delete: true },
    housekeeping: { create: true, read: true, update: true, delete: true },
    maintenance: { create: true, read: true, update: true, delete: true },
    reports: { create: true, read: true, update: true, delete: true },
  },
  hoteladmin: {
    bookings: { create: true, read: true, update: true, delete: true },
    rooms: { create: true, read: true, update: true, delete: true },
    guests: { create: true, read: true, update: true, delete: true },
    staff: { create: true, read: true, update: true, delete: true },
    payments: { create: true, read: true, update: true, delete: true },
    menuItems: { create: true, read: true, update: true, delete: true },
    restaurantOrders: { create: true, read: true, update: true, delete: true },
    housekeeping: { create: true, read: true, update: true, delete: true },
    maintenance: { create: true, read: true, update: true, delete: true },
    reports: { create: true, read: true, update: true, delete: true },
  },
  frontdesk: {
    bookings: { create: true, read: true, update: true, delete: true },
    rooms: { create: false, read: true, update: true, delete: false },
    guests: { create: true, read: true, update: true, delete: false },
    staff: { create: false, read: false, update: false, delete: false },
    payments: { create: true, read: true, update: true, delete: false },
    menuItems: { create: false, read: true, update: false, delete: false },
    restaurantOrders: { create: true, read: true, update: true, delete: false },
    housekeeping: { create: false, read: true, update: true, delete: false },
    maintenance: { create: false, read: true, update: false, delete: false },
    reports: { create: false, read: true, update: false, delete: false },
  },
  housekeeper: {
    bookings: { create: false, read: false, update: false, delete: false },
    rooms: { create: false, read: true, update: true, delete: false },
    guests: { create: false, read: false, update: false, delete: false },
    staff: { create: false, read: false, update: false, delete: false },
    payments: { create: false, read: false, update: false, delete: false },
    menuItems: { create: false, read: false, update: false, delete: false },
    restaurantOrders: {
      create: false,
      read: false,
      update: false,
      delete: false,
    },
    housekeeping: { create: false, read: true, update: true, delete: false },
    maintenance: { create: true, read: true, update: true, delete: false },
    reports: { create: false, read: false, update: false, delete: false },
  },
  maintenance: {
    bookings: { create: false, read: false, update: false, delete: false },
    rooms: { create: false, read: true, update: true, delete: false },
    guests: { create: false, read: false, update: false, delete: false },
    staff: { create: false, read: false, update: false, delete: false },
    payments: { create: false, read: false, update: false, delete: false },
    menuItems: { create: false, read: false, update: false, delete: false },
    restaurantOrders: {
      create: false,
      read: false,
      update: false,
      delete: false,
    },
    housekeeping: { create: false, read: true, update: true, delete: false },
    maintenance: { create: true, read: true, update: true, delete: false },
    reports: { create: false, read: false, update: false, delete: false },
  },
  accountant: {
    bookings: { create: false, read: true, update: false, delete: false },
    rooms: { create: false, read: true, update: false, delete: false },
    guests: { create: false, read: true, update: false, delete: false },
    staff: { create: false, read: true, update: false, delete: false },
    payments: { create: true, read: true, update: true, delete: false },
    menuItems: { create: false, read: true, update: false, delete: false },
    restaurantOrders: {
      create: false,
      read: true,
      update: false,
      delete: false,
    },
    housekeeping: { create: false, read: false, update: false, delete: false },
    maintenance: { create: false, read: false, update: false, delete: false },
    reports: { create: false, read: true, update: false, delete: false },
  },
  restaurantmanager: {
    bookings: { create: false, read: true, update: false, delete: false },
    rooms: { create: false, read: true, update: false, delete: false },
    guests: { create: false, read: true, update: false, delete: false },
    staff: { create: false, read: true, update: false, delete: false },
    payments: { create: true, read: true, update: true, delete: false },
    menuItems: { create: true, read: true, update: true, delete: true },
    restaurantOrders: { create: true, read: true, update: true, delete: true },
    housekeeping: { create: false, read: false, update: false, delete: false },
    maintenance: { create: false, read: false, update: false, delete: false },
    reports: { create: true, read: true, update: false, delete: false },
  },
  chef: {
    bookings: { create: false, read: false, update: false, delete: false },
    rooms: { create: false, read: false, update: false, delete: false },
    guests: { create: false, read: false, update: false, delete: false },
    staff: { create: false, read: false, update: false, delete: false },
    payments: { create: false, read: false, update: false, delete: false },
    menuItems: { create: false, read: true, update: true, delete: false },
    restaurantOrders: {
      create: false,
      read: true,
      update: true,
      delete: false,
    },
    housekeeping: { create: false, read: false, update: false, delete: false },
    maintenance: { create: false, read: false, update: false, delete: false },
    reports: { create: false, read: false, update: false, delete: false },
  },
  securitystaff: {
    bookings: { create: false, read: true, update: false, delete: false },
    rooms: { create: false, read: true, update: false, delete: false },
    guests: { create: false, read: true, update: false, delete: false },
    staff: { create: false, read: true, update: false, delete: false },
    payments: { create: false, read: false, update: false, delete: false },
    menuItems: { create: false, read: false, update: false, delete: false },
    restaurantOrders: {
      create: false,
      read: false,
      update: false,
      delete: false,
    },
    housekeeping: { create: false, read: true, update: false, delete: false },
    maintenance: { create: false, read: true, update: false, delete: false },
    reports: { create: false, read: false, update: false, delete: false },
  },

  guest: {
    bookings: { create: true, read: true, update: true, delete: false },
    rooms: { create: false, read: true, update: false, delete: false },
    guests: { create: false, read: true, update: true, delete: false },
    staff: { create: false, read: false, update: false, delete: false },
    payments: { create: true, read: true, update: false, delete: false },
    menuItems: { create: false, read: true, update: false, delete: false },
    restaurantOrders: {
      create: true,
      read: true,
      update: false,
      delete: false,
    },
    housekeeping: { create: true, read: true, update: true, delete: false },
    maintenance: { create: true, read: true, update: false, delete: false },
    reports: { create: false, read: false, update: false, delete: false },
  },
};

export { createDefaultPermissions, rolePermissions };
