const createDefaultPermissions = () => ({
  bookings: {
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  rooms: {
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  guests: {
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  users: {
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  payment: {
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  menu: {
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  restaurant: {
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  housekeeping: {
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  maintenance: {
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  billing: {
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  reports: {
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  notifications: {
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  roles: {
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  permissions: {
    create: false,
    read: false,
    update: false,
    delete: false,
  },
});

const rolePermissions = {
  superadmin: {
    bookings: { create: true, read: true, update: true, delete: true },
    rooms: { create: true, read: true, update: true, delete: true },
    guests: { create: true, read: true, update: true, delete: true },
    users: { create: true, read: true, update: true, delete: true },
    payment: { create: true, read: true, update: true, delete: true },
    menu: { create: true, read: true, update: true, delete: true },
    restaurant: { create: true, read: true, update: true, delete: true },
    housekeeping: { create: true, read: true, update: true, delete: true },
    maintenance: { create: true, read: true, update: true, delete: true },
    billing: { create: true, read: true, update: true, delete: true },
    reports: { create: true, read: true, update: true, delete: true },
    notifications: { create: true, read: true, update: true, delete: true },
    roles: { create: true, read: true, update: true, delete: true },
    permissions: { create: true, read: true, update: true, delete: true },
  },
  hoteladmin: {
    bookings: { create: true, read: true, update: true, delete: true },
    rooms: { create: true, read: true, update: true, delete: true },
    guests: { create: true, read: true, update: true, delete: true },
    users: { create: true, read: true, update: true, delete: true },
    payment: { create: true, read: true, update: true, delete: true },
    menu: { create: true, read: true, update: true, delete: true },
    restaurant: { create: true, read: true, update: true, delete: true },
    housekeeping: { create: true, read: true, update: true, delete: true },
    maintenance: { create: true, read: true, update: true, delete: true },
    billing: { create: true, read: true, update: true, delete: true },
    reports: { create: true, read: true, update: true, delete: true },
    notifications: { create: true, read: true, update: true, delete: true },
    roles: { create: true, read: true, update: true, delete: true },
    permissions: { create: true, read: true, update: true, delete: true },
  },
  frontdesk: {
    bookings: { create: true, read: true, update: true, delete: true },
    rooms: { create: false, read: true, update: true, delete: false },
    guests: { create: true, read: true, update: true, delete: false },
    users: { create: false, read: false, update: false, delete: false },
    payment: { create: true, read: true, update: true, delete: false },
    menu: { create: false, read: true, update: false, delete: false },
    restaurant: { create: true, read: true, update: true, delete: false },
    housekeeping: { create: false, read: true, update: true, delete: false },
    maintenance: { create: false, read: true, update: false, delete: false },
    billing: { create: true, read: true, update: true, delete: false },
    reports: { create: false, read: true, update: false, delete: false },
    notifications: { create: false, read: true, update: false, delete: false },
    roles: { create: false, read: false, update: false, delete: false },
    permissions: { create: false, read: false, update: false, delete: false },
  },
  housekeeper: {
    bookings: { create: false, read: false, update: false, delete: false },
    rooms: { create: false, read: true, update: true, delete: false },
    guests: { create: false, read: false, update: false, delete: false },
    users: { create: false, read: false, update: false, delete: false },
    payment: { create: false, read: false, update: false, delete: false },
    menu: { create: false, read: false, update: false, delete: false },
    restaurant: { create: false, read: false, update: false, delete: false },
    housekeeping: { create: false, read: true, update: true, delete: false },
    maintenance: { create: true, read: true, update: true, delete: false },
    billing: { create: false, read: false, update: false, delete: false },
    reports: { create: false, read: false, update: false, delete: false },
    notifications: { create: false, read: false, update: false, delete: false },
    roles: { create: false, read: false, update: false, delete: false },
    permissions: { create: false, read: false, update: false, delete: false },
  },
  maintenance: {
    bookings: { create: false, read: false, update: false, delete: false },
    rooms: { create: false, read: true, update: true, delete: false },
    guests: { create: false, read: false, update: false, delete: false },
    users: { create: false, read: false, update: false, delete: false },
    payment: { create: false, read: false, update: false, delete: false },
    menu: { create: false, read: false, update: false, delete: false },
    restaurant: { create: false, read: false, update: false, delete: false },
    housekeeping: { create: false, read: true, update: true, delete: false },
    maintenance: { create: true, read: true, update: true, delete: false },
    billing: { create: false, read: false, update: false, delete: false },
    reports: { create: false, read: false, update: false, delete: false },
    notifications: { create: false, read: false, update: false, delete: false },
    roles: { create: false, read: false, update: false, delete: false },
    permissions: { create: false, read: false, update: false, delete: false },
  },
  accountant: {
    bookings: { create: false, read: true, update: false, delete: false },
    rooms: { create: false, read: true, update: false, delete: false },
    guests: { create: false, read: true, update: false, delete: false },
    users: { create: false, read: true, update: false, delete: false },
    payment: { create: true, read: true, update: true, delete: false },
    menu: { create: false, read: true, update: false, delete: false },
    restaurant: { create: false, read: true, update: false, delete: false },
    housekeeping: { create: false, read: false, update: false, delete: false },
    maintenance: { create: false, read: false, update: false, delete: false },
    billing: { create: true, read: true, update: true, delete: false },
    reports: { create: false, read: true, update: false, delete: false },
    notifications: { create: false, read: true, update: false, delete: false },
    roles: { create: false, read: false, update: false, delete: false },
    permissions: { create: false, read: false, update: false, delete: false },
  },
  restaurantmanager: {
    bookings: { create: false, read: true, update: false, delete: false },
    rooms: { create: false, read: true, update: false, delete: false },
    guests: { create: false, read: true, update: false, delete: false },
    users: { create: false, read: true, update: false, delete: false },
    payment: { create: true, read: true, update: true, delete: false },
    menu: { create: true, read: true, update: true, delete: true },
    restaurant: { create: true, read: true, update: true, delete: true },
    housekeeping: { create: false, read: false, update: false, delete: false },
    maintenance: { create: false, read: false, update: false, delete: false },
    billing: { create: false, read: true, update: false, delete: false },
    reports: { create: true, read: true, update: false, delete: false },
    notifications: { create: false, read: true, update: false, delete: false },
    roles: { create: false, read: false, update: false, delete: false },
    permissions: { create: false, read: false, update: false, delete: false },
  },
  chef: {
    bookings: { create: false, read: false, update: false, delete: false },
    rooms: { create: false, read: false, update: false, delete: false },
    guests: { create: false, read: false, update: false, delete: false },
    users: { create: false, read: false, update: false, delete: false },
    payment: { create: false, read: false, update: false, delete: false },
    menu: { create: false, read: true, update: true, delete: false },
    restaurant: { create: false, read: true, update: true, delete: false },
    housekeeping: { create: false, read: false, update: false, delete: false },
    maintenance: { create: false, read: false, update: false, delete: false },
    billing: { create: false, read: false, update: false, delete: false },
    reports: { create: false, read: false, update: false, delete: false },
    notifications: { create: false, read: false, update: false, delete: false },
    roles: { create: false, read: false, update: false, delete: false },
    permissions: { create: false, read: false, update: false, delete: false },
  },
  securitystaff: {
    bookings: { create: false, read: true, update: false, delete: false },
    rooms: { create: false, read: true, update: false, delete: false },
    guests: { create: false, read: true, update: false, delete: false },
    users: { create: false, read: true, update: false, delete: false },
    payment: { create: false, read: false, update: false, delete: false },
    menu: { create: false, read: false, update: false, delete: false },
    restaurant: { create: false, read: false, update: false, delete: false },
    housekeeping: { create: false, read: true, update: false, delete: false },
    maintenance: { create: false, read: true, update: false, delete: false },
    billing: { create: false, read: false, update: false, delete: false },
    reports: { create: false, read: false, update: false, delete: false },
    notifications: { create: false, read: false, update: false, delete: false },
    roles: { create: false, read: false, update: false, delete: false },
    permissions: { create: false, read: false, update: false, delete: false },
  },

  guest: {
    bookings: { create: true, read: true, update: true, delete: false },
    rooms: { create: false, read: true, update: false, delete: false },
    guests: { create: false, read: false, update: false, delete: false },
    users: { create: false, read: false, update: false, delete: false },
    payment: { create: true, read: true, update: false, delete: false },
    menu: { create: false, read: true, update: false, delete: false },
    restaurant: { create: true, read: true, update: false, delete: false },
    housekeeping: { create: false, read: false, update: false, delete: false },
    maintenance: { create: false, read: false, update: false, delete: false },
    billing: { create: false, read: false, update: false, delete: false },
    reports: { create: false, read: false, update: false, delete: false },
    notifications: { create: false, read: false, update: false, delete: false },
    roles: { create: false, read: false, update: false, delete: false },
    permissions: { create: false, read: false, update: false, delete: false },
  },
};

export { createDefaultPermissions, rolePermissions };