import {
  LayoutDashboard,
  Users,
  Shield,
  KeyRound,
  BedDouble,
  CalendarCheck,
  DoorOpen,
  Sparkles,
  Wrench,
  ReceiptText,
  UtensilsCrossed,
  Coffee,
  UserRound,
  BarChart3,
  ScrollText,
  Settings,
} from "lucide-react";

export const sidebarItems = [
  { label: "Dashboard", path: "/dashboard", module: "dashboard", Icon: LayoutDashboard },
  { label: "Users", path: "/users", module: "users", Icon: Users },
  { label: "Roles", path: "/roles", module: "roles", Icon: Shield },
  { label: "Permissions", path: "/permissions", module: "permissions", Icon: KeyRound },
  { label: "Rooms", path: "/rooms", module: "rooms", Icon: BedDouble },
  { label: "Bookings", path: "/bookings", module: "bookings", Icon: CalendarCheck },
  { label: "Check In / Out", path: "/checkin-checkout", module: "checkin-checkout", Icon: DoorOpen },
  { label: "Housekeeping", path: "/housekeeping", module: "housekeeping", Icon: Sparkles },
  { label: "Maintenance", path: "/maintenance", module: "maintenance", Icon: Wrench },
  { label: "Billing", path: "/billing", module: "billing", Icon: ReceiptText },
  { label: "Restaurant", path: "/restaurant", module: "restaurant", Icon: UtensilsCrossed },
  { label: "Menu", path: "/menu", module: "menu", Icon: Coffee },
  { label: "Guests", path: "/guests", module: "guests", Icon: UserRound },
  { label: "Reports", path: "/reports", module: "reports", Icon: BarChart3 },
  { label: "Audit Logs", path: "/audit-logs", module: "audit-logs", Icon: ScrollText },
  { label: "Settings", path: "/settings", module: "settings", Icon: Settings },
];